version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "IftttCallBackApi"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-efwgqrdbequv"
s3_prefix = "IftttCallBackApi"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

